spring:
  profiles:
    active: dev



#logging:
#  level:
#    com:
#      example:
#        demo: DEBUG

jwt:
  secretKey: Y0uR$up3rS3cr3tJWTKeyForEncryption@2025





server:
  servlet:
    context-path: /teamfinder

